version: '3.9'

services:
  back:
    build:
      context: ./back
    command: npm run start:dev
    env_file: .env
    ports:
      - "${BACK_PORT:-3001}:3001"
    volumes:
      - ./back:/app
    working_dir: /app

  front:
    build:
      context: ./front
    command: npm run dev
    env_file: .env
    ports:
      - "${FRONT_PORT:-3000}:3000"
    volumes:
      - ./front:/app
    working_dir: /app
